#!/bin/bash
for i in 1 2 3 4 5 6 7 8 9 10
do
    python create_mask.py --dataset cifar10 --mask-type given \
        --n-repeats 10 --given-mask-path ./given_masks/cifar_rf_${i}.npy \
        --slurm-friendly --random-change-iter 48
done
