#!/bin/bash
for i in 1 2 3 4 5 6 7 8 9 10
do
    python create_mask.py --dataset fashion_mnist --mask-type given \
        --n-repeats 10 --given-mask-path ./given_masks/fmnist_rf_${i}.npy \
        --input-drop-upscaling False --slurm-friendly --random-change-iter 245
done
