#!/bin/bash
python create_mask.py --dataset cifar10 --mask-type static \
    --n-repeats 10 --lambda-init 1 \
    --lr 0.001 --lambda-factor 1.25 --any-granularity channel \
    --use-warmup-net 1 --n-epochs 300 --lambda-patience 5