#!/bin/bash
python create_mask.py --dataset supernova --mask-type static \
    --n-repeats 10 --lambda-init 1 \
    --lr 0.001 --lambda-factor 1.1 --any-granularity channel \
    --use-warmup-net 1 --n-epochs 400 --lambda-patience 5